### ISSUE TITLE
New way to ban

### ISSUE THREAD

**Issue by ChuckDoll** [fr34kyn01535/GlobalBan#11]
Hey Freakyn.
Why don't you make something with MAC ban? 
It's better than ip, ID64 and will hold some multi accounts hackers. 
Can you think about that? 
Thanks again! 
By the way. I'm trying to learn this C++ language to help you guys on it. 
ChuckDoll

**Comment by fr34kyn01535** [comment]
MAC adresses of computers connecting via modem to the ISP or the MAC adress of those modems that are peer to the ISP are not exposed on the Internet. While in IPv6 you might be lucky the ISP does use MAC address of modem or computer it is not possible to retrieve such information over IPv4. Sorry, but its not possible.
